// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgavinkahajcgxsqxhna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnYXZpbmthaGFqY2d4c3F4aG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjI2NjgsImV4cCI6MjA3MDM5ODY2OH0.hRJWS7BOc66naPufQx9hmLEzRB0GPjYuD3i8GIvbprQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});